### ISSUE TITLE
Incorrect text styles in Overview page

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/creativecommons-certificate#24]
## Description
**Page: Overview**
The following states are incorrect:
1. The "Creative Commons Certificate" title should have the `Heading 2A` style.
2. The stats' name should have the `Heading 5A` style. With more line-height. 
3. The stat's value should have the `value` style.

## Screenshots
<img width="841" alt="Screen Shot 2020-11-26 at 17 11 59" src="https://user-images.githubusercontent.com/895819/100388953-ceaa3700-300a-11eb-91b3-a49a980bb0ee.png">

**Comment by zackkrida** [comment]
<img width="675" alt="2020-12-07-72" src="https://user-images.githubusercontent.com/6351754/101460625-ed97ab80-38dd-11eb-93e1-603c56e10eb9.png">

I added the line-height, but the 1 and 3 seem already done to me.

**Comment by panchovm** [comment]
To confirm, I'm seeing [this site](https://tempcert.creativecommons.org/). And using [this tool](http://www.chengyinliu.com/whatfont.html) to see text style's details I notice the following:

1. The "creative commons certificate" text has these specs
<img width="375" alt="Screen Shot 2020-12-08 at 10 49 40" src="https://user-images.githubusercontent.com/895819/101491992-261da080-3943-11eb-8396-60e5491cfe8b.png">

3. The stat's value uses `source sans pro` instead of `roboto condensed`.
<img width="366" alt="Screen Shot 2020-12-08 at 10 50 51" src="https://user-images.githubusercontent.com/895819/101492111-4cdbd700-3943-11eb-83b1-520d361ba42e.png">
